include:
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /templates.gitlab-ci.yaml
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /jobs/analyze_package.gitlab-ci.yaml
  - project: ihp/julia/julia-gitlab-ci-templates
    ref: v1.5.0
    file: /jobs/analyze_tests.gitlab-ci.yaml

analyze_tests:
  variables:
    CI_JULIA_JET_TARGET_DEFINED_MODULES: "true"

test: &test
  stage: test
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.0", "1.3", "1.6", "1"]
  extends:
    - .julia.setup
    - .julia.test

test without threads:
  << : *test
  variables:
    CI_JULIA_TEST_THREADS: THREADS_OFF
