name = "ResourcePools"
uuid = "16787047-0d73-522e-b8c7-4a818d739b35"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.15.0, 0.18"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
